Shopy/Shopy/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

Shopy/main/urls.py
from django.urls import path, include
from rest_framework import routers
from . import models, views
from django.views.generic import DetailView, TemplateView
from . import forms
from django.contrib.auth import views as auth_views
from . import endpoints

router=routers.DefaultRouter()
router.register(r'orderlines', endpoints.PaidOrderLineViewSet)
router.register(r'orders', endpoints.PaidOrderViewSet)



urlpatterns = [
    path('', views.home, name='home'),
    path('product/<slug:slug>/', views.ProductView.as_view(),
        name='product'),
    path('products/<slug:tag>/', views.ProductListView.as_view(),
        name='products'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(
            template_name='main/login.html',
            form_class=forms.AuthenticationForm,
        ),
        name='login',

    ),
    path('address/', views.AddressListView.as_view(),
        name='address_list'),
    path('address/create/', views.AddressCreateView.as_view(),
        name='address_create'),
    path('address/<int:pk>/', views.AddressUpdateView.as_view(),
        name='address_update'),
    path('address/<int:pk>/delete/', views.AddressDeleteView.as_view(),
        name='address_delete'),

    path('add_to_basket/', views.add_to_basket, name='add_to_basket'),
    path('basket/', views.manage_basket, name='basket'),

    path("order/done/", TemplateView.as_view(template_name='order_name.html'),
        name="checkout_done"),

    path("order/address_select/", views.AddressSelectionView.as_view(),
        name="address_select"),



    path('api/', include(router.urls)),

    path("customer-service/<int:order_id>/", views.room, name="cs_chat"),

]

Shopy/main/models.py
from django.db import models
from django.contrib.auth.models import (
    AbstractUser,
    BaseUserManager
)
from django.core.validators import MinValueValidator

class UserManager(BaseUserManager):
    use_in_migrations=True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("The given email must be set")
        email=self.normalize_email(email)
        user=self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)


    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(
                "Superuser must have is_staff=True"
            )
        if extra_fields.get("is_superuser") is not True:
            raise ValueError(
                "Superuser must have is superuser=True."
            )
        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username=None
    email=models.EmailField('email address', unique=True)

    USERNAME_FIELD='email'
    REQUIRED_FIELDS=[]
    objects=UserManager()


class ProductTagManager(models.Manager):
    def get_by_natural_key(self, slug):
        return self.get(slug=slug)


class ProductTag(models.Model):
    name=models.CharField(max_length=32)
    slug=models.SlugField(max_length=48)
    description=models.TextField(blank=True)
    active=models.BooleanField(default=True)

    objects=ProductTagManager()

    def __str__(self):
        return self.name

    def natural_key(self):
        return (self.slug,)


# Create your models here.
class ActiveManager(models.Manager):
    def active(self):
        return self.filter(active=True)


class Product(models.Model):
    name=models.CharField(max_length=32)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=12, decimal_places=2)
    slug=models.SlugField(max_length=48)
    active=models.BooleanField(default=True)
    in_stock=models.BooleanField(default=True)
    date_update=models.DateTimeField(auto_now=True)

    tags=models.ManyToManyField(ProductTag, blank=True)

    objects=ActiveManager()

    def __str__(self):
        return f"{self.name}"


class ProductImage(models.Model):
    product=models.ForeignKey(
        Product, on_delete=models.CASCADE
    )
    thumbnail=models.ImageField(
        upload_to="product-thumbnails", null=True
    )
    image=models.ImageField(upload_to='product-images')

class Address(models.Model):
    SUPPORTED_COUNTRIES=(
        ('uk', 'United Kingdom'),
        ('us', 'United States of America'),
    )

    user=models.ForeignKey(User, on_delete=models.CASCADE)
    name=models.CharField(max_length=60)
    address1=models.CharField("Address line 1", max_length=60)
    address2=models.CharField(
        "Address line 2", max_length=60, blank=True
    )
    zip_code=models.CharField(
        "ZIP / Postal code", max_length=12
    )
    city=models.CharField(max_length=60)
    country=models.CharField(
        max_length=3, choices=SUPPORTED_COUNTRIES
    )

    def __str__(self):
        return ", ".join(
            [
                self.name,
                self.address1,
                self.address2,
                self.zip_code,
                self.city,
                self.country,
            ]
        )

class Basket(models.Model):
    OPEN=10
    SUBMITTED=20
    STATUSES=((OPEN, "OPEN"), (SUBMITTED, "Submitted"))

    user=models.ForeignKey(
        User, on_delete=models.CASCADE, blank=True, null=True
    )
    status=models.IntegerField(choices=STATUSES, default=OPEN)

    def is_empty(self):
        return self.basketline_set.all().count()==0

    def count(self):
        return sum(i.quantity for i in self.basketline_set.all())


class BasketLine(models.Model):
    basket=models.ForeignKey(Basket, on_delete=models.CASCADE)
    product=models.ForeignKey(
        Product, on_delete=models.CASCADE
    )
    quantity=models.PositiveIntegerField(
        default=1, validators=[MinValueValidator(1)]
    )#We make sure that the value of the quantity field is never below one



class Order(models.Model):
    NEW=10
    PAID=20
    DONE=30
    STATUSES=((NEW, "New"), (PAID, "Paid"), (DONE, "Done"))

    user=models.ForeignKey(User, on_delete=models.CASCADE)
    status=models.IntegerField(choices=STATUSES, default=NEW)

    last_spoken_to=models.ForeignKey(User, null=True,
        related_name="cs_chats",
        on_delete=models.SET_NULL,
    )

    billing_name=models.CharField(max_length=60)
    billing_address1=models.CharField(max_length=60)
    billing_address2=models.CharField(max_length=60, blank=True)
    billing_zip_code=models.CharField(max_length=12)
    billing_city=models.CharField(max_length=60)
    billing_country=models.CharField(max_length=3)

    shipping_name=models.CharField(max_length=60)
    shipping_address1=models.CharField(max_length=60)
    shipping_address2=models.CharField(max_length=60, blank=True)
    shipping_zip_code = models.CharField(max_length=12)
    shipping_city = models.CharField(max_length=60)
    shipping_country = models.CharField(max_length=3)

    date_updated = models.DateTimeField(auto_now=True)
    date_added = models.DateTimeField(auto_now_add=True)


class OrderLine(models.Model):
    NEW = 10
    PROCESSING = 20
    SENT = 30
    CANCELLED = 40
    STATUSES = (
        (NEW, "New"),
        (PROCESSING, "Processing"),
        (SENT, "Sent"),
        (CANCELLED, "Cancelled"),
    )
    order = models.ForeignKey(
        Order, on_delete=models.CASCADE, related_name="lines"
    )
    product = models.ForeignKey(
    Product, on_delete=models.PROTECT
    )
    status = models.IntegerField(choices=STATUSES, default=NEW)

Shopy/main/views.py
from django.shortcuts import render
from .models import Product
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    DeleteView,
    UpdateView,
    FormView
)
from main import forms
from django.shortcuts import get_object_or_404
from . import models
import logging
from django.contrib.auth import login, authenticate
from django.contrib import messages
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render






logger=logging.getLogger(__name__)

# Create your views here.
def home(request):
    return render(request, 'main/home.html')


class ProductView(DetailView):
    model=Product
    template_name='main/product_detail.html'



class ProductListView(ListView):
    model=Product
    paginate_by=4
    template_name='main/product_list.html'

    def get_queryset(self):
        tag=self.kwargs['tag']
        self.tag=None
        if tag != "all":
            self.tag=get_object_or_404(models.ProductTag, slug=tag)
        if self.tag:
            products=Product.objects.active().filter(tag=self.tag)
        else:
            products=models.Product.objects.active()
        return products.order_by("name")


class SignupView(FormView):
    template_name='main/signup.html'
    form_class=forms.UserCreationForm

    def get_success_url(self):
        redirect_to=self.request.GET.get('next', '/')
        return redirect_to

    def form_valid(self, form):
        response=super().form_valid(form)
        form.save()
        email=form.cleaned_data.get("email")
        raw_password=form.claned_data.get("password1")
        logger.info(
            "New signup for email=%s through SignUpView", email
        )
        user=authenticate(email=email, password=raw_password)
        login(self.request, user)
        form.send_email()

        messages.info(
            self.request, "You signed up successfully"
        )
        return response



class AddressListView(LoginRequiredMixin, ListView):
    model=models.Address
    template_name='main/address_list.html'

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class AddressCreateView(LoginRequiredMixin, CreateView):
    model=models.Address
    fields=[
        'name',
        'address1',
        'address2',
        'zip_code',
        'city',
        'country',
    ]
    template_name='main/address_form.html'
    success_url=reverse_lazy('address_list')

    def form_valid(self, form):
        obj=form.save(commit=False)
        obj.user=self.request.user
        obj.save()
        return super().form_valid(form)

class AddressUpdateView(LoginRequiredMixin, UpdateView):
    model=models.Address
    fields=[
        'name',
        'address1',
        'address2',
        'zip_code',
        'city',
        'country',
    ]
    template_name='main/address_update.html'
    success_url=reverse_lazy('address_list')

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)
        #Each user must be able to operate only on their own address

class AddressDeleteView(LoginRequiredMixin, DeleteView):
    model=models.Address
    success_url=reverse_lazy('address_list')
    template_name='main/address_delete.html'

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)
#(LoginRequiredMixin, DeleteView)

def add_to_basket(request):
    product=get_object_or_404(
        models.Product, pk=request.GET.get("product_id")
    )
    basket=request.basket#will work only if basket exists and its id is in
    #the session already
    if not request.basket:
        if request.user.is_authenticated:
            user=request.user
        else:
            user=None
        basket=models.Basket.objects.create(user=user)
        request.session['basket_id']=basket.id
    basketline, created=models.BasketLine.objects.get_or_create(
        basket=basket, product=product
    )
    if not created:
        basketline.quantity+=1
        basketline.save()
    return HttpResponseRedirect(
        reverse("product", args=(product.slug,))
    )


def manage_basket(request):
    if not request.basket:
        return render(request, "main/basket.html", {"formset":None})
    if request.method=="POST":
        formset=forms.BasketLineFormSet(
            request.POST, instance=request.basket
        )
        if formset.is_valid():
            formset.save()
    else:
        formset=forms.BasketLineFormSet(
            instance=request.basket
        )
    if request.basket.is_empty():
        return render(request, "main/basket.html", {"formset":None})
    return render(request, "main/basket.html", {"formset":formset})



def create_order(self, billing_address, shipping_address):
    if not self.user:
        raise exceptions.BasketException(
            "Cannot create order without user"
        )
    logger.info(
        "Creating order for basket_id=%d"
        ", shipping_address_id=%d, billing_address_id=%d",
        self.id,
        shipping_address.id,
        billing_address.id,
    )
    order_data = {
            "user":self.user,
            "billing_name": billing_address.name,
            "billing_address1": billing_address.address1,
            "billing_address2": billing_address.address2,
            "billing_zip_code": billing_address.zip_code,
            "billing_city": billing_address.city,
            "billing_country": billing_address.country,
            "shipping_name": shipping_address.name,
            "shipping_address1": shipping_address.address1,
            "shipping_address2": shipping_address.address2,
            "shipping_zip_code": shipping_address.zip_code,
            "shipping_city": shipping_address.city,
            "shipping_country": shipping_address.country,
        }
    order = Order.objects.create(**order_data)
    c=0
    for line in self.basketline_set.all():
        for item in range(line.quantity):
            order_line_data = {
                    "order": order,
                    "product": line.product,
            }
            order_line = OrderLine.objects.create(
                    **order_line_data
            )
            c += 1
    logger.info(
            "Created order with id=%d and lines_count=%d",
            order.id,
            c,
        )
    self.status = Basket.SUBMITTED
    self.save()
    return order


class AddressSelectionView(LoginRequiredMixin, FormView):
    template_name="address_select.html"
    form_class=forms.AddressSelectionForm
    success_url=reverse_lazy('checkout_done')

    def get_form_kwargs(self):
        kwargs=super().get_form_kwargs()
        kwargs['user']=self.request.user
        return kwargs

    def form_valid(self, form):
        del self.request.session['basket_id']
        basket=self.request.basket
        basket.create_object(
            form.cleaned_data['billing_address'],
            form.cleaned_data['shipping_address']
        )
        return super().form_valid(form)

def room(request, order_id):
    return render(
        request,
        "main/chat_room.html",
        {"room_name_json":str(order_id)},
    )

Shopy/main/templates/main/address_delete.html
{% extends "base.html" %}
{% block content %}
  <h2>Delete address</h2>
  <form method="POST">
    {%  csrf_token %}
    <p>Are you sure you want to delete it?</p>
     <button type="submit" class="btn btn-­primary">Submit
</button>
  </form>
{% endblock content %}

Shopy/main/templates/main/address_form.html
{% extends "base.html" %}
{% block content %}
<h2>Add a new address</h2>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-­primary">Submit</button>
</form>
{% endblock content %}

Shopy/main/templates/main/address_list.html
{% extends "base.html" %}
{% block content %}
  <h1>List of your addresses:</h1>
  {% for address in object_list %}
    <p>
      {{ address.name }}<br>
      {{ address.address1 }}<br>
      {{ address.address2 }}<br>
      {{ address.city }}<br>
      {{ address.get_country_display }}<br>
    </p>
    <p>
      <a href="{% url "address_update" address.id %}">Update
address</a>
    </p>
    <p>
       <a href="{% url "address_delete" address.id %}">Delete
address</a>
    </p>
    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %}
  <p>
    <a href="{% url "address_create" %}">Add new address</a>
  </p>
{% endblock content %}

Shopy/main/templates/main/address_update.html
{% extends "base.html" %}
{% block content %}
  <h2>Add a new address</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
     <button type="submit" class="btn btn-­primary">Submit</button>
  </form>
{% endblock content %}

Shopy/main/templates/main/basket.html
{% extends "base.html" %}
{% block content %}
  <h2>Basket</h2>
  {% if formset %}
    <p>You can adjust the quantities below.</p>
    <form method="POST">
      {% csrf_token %}
      {{ formset.management_form }}
      {% for form in formset %}
        <p>
          {{ form.instance.product.name }}
          {{ form }}
        </p>
      {% endfor %}
       <button type="submit" class="btn btn-­default">Update basket</button>
      {% if user.is_authenticated %}
         <a href="{% url 'address_select' %}" class="btn btn-primary">Place order</a>
      {% else %}
        <a href="{% url "signup" %}?next={% url "address_select" %}" class="btn btn-primary">Signup</a>
        <a href="{% url "login" %}?next={% url "address_select" %}" class="btn btn-primary">Login</a>
      {% endif %}
    </form>
  {% else %}
    <p>You have no items in the basket.</p>
  {% endif %}
{% endblock content %}
{% block js %}
  {% if formset %}
    {{ formset.media }}
  {% endif %}
{% endblock js %}

Shopy/main/templates/main/home.html
{% extends "base.html" %}
{% block content %}
  <h2>Home</h2>
  <p>this will be the content of home</p>
{% endblock content %}

Shopy/main/templates/main/login.html
{% extends "base.html" %}
{% block content %}
<h2>Login</h2>
<p>Please fill the form below.</p>
<form method="POST">
  {% csrf_token %}
  {{ form.non_field_errors }}
  <div class="form-group">
    {{ form.email.label_tag }}
    <input
      type="email"
      class="form-control {% if form.email.errors %}
is-­invalid{% endif %}"
      id="id_email"
      name="email"
      placeholder="Your email"
      value="{{ form.email.value|default:"" }}">
    {% if form.email.errors %}
      <div class="invalid-feedback">
        {{ form.email.errors }}
      </div>
    {% endif %}
  </div>
  <div class="form-group">
    {{ form.password.label_tag }}
    <input
      type="password"
      class="form-control{% if form.password.errors %}
is-­invalid{% endif %}"
      id="id_password"
      name="password"
      value="{{ form.password.value|default:"" }}">
      {% if form.password.errors %}
      <div class="invalid-feedback">
        {{ form.password.errors }}
      </div>
    {% endif %}
  </div>
  <button type="submit" class="btn btn-­primary">Submit</button>
</form>
{% endblock content %}

Shopy/main/templates/main/product_detail.html
{% extends "base.html" %}
{% block content %}
   <h1>products</h1>
    <table class="table">
     <tr>
       <th>Name</th>
       <td>{{ object.name }}</td>
     </tr>
     <tr>
       <th>Cover images</th>
       <td>
         <div id="imagebox">
           {% for image in object.productimage_set.all %}
            <img src="{{ image.thumbnail.url }}" alt="cover"/>
          {% endfor %}
         </div>
       </td>
     </tr>
     <tr>
     <th>Price</th>
     <td>{{ object.price }}</td>
     </tr>
     <tr>
       <th>Description</th>
       <td>{{ object.description|linebreaks }}</td>
     </tr>
     <tr>
       <th>Tags</th>
        <td>{{ object.tags.all|join:","|default:"No tags available" }}</td>
     </tr>
     <tr>
       <th>In stock</th>
       <td>{{ object.in_stock|yesno|capfirst }}</td>
     </tr>
     <tr>
       <th>Updated</th>
       <td>{{ object.date_updated|date:"F Y" }}</td>
     </tr>

    <a href="{% url 'add_to_basket' %}?product_id={{object.id}}">
       Add to basket
    </a>
 </table>
{% endblock content %}
{% block js %}
<script
  src="https://unpkg.com/react@16/umd/react.production.min.js">
</script>
<script
  src="https://unpkg.com/react-dom@16/umd/react-dom.production.
min.js">
</script>
<style type="text/css" media="screen">
.image{
    margin: 10px;
    display: inline-block;
}
</style>
<script>
const e=React.createElement;
class ImageBox extends React.Component{
  constructor(props){
    super(props);
    this.state = {
        currentImage: this.props.imageStart
    }
  }
  click(image){
    this.setState({
      currentImage: image
  });
}
render(){
  const images = this.props.images.map((i)=>
     e('div', {className: "image", key: i.id},
      e('img', {onClick: this.click.bind(this, i),
               width: "100",
               src: i.thumbnail}),
      ),
  );
  return e('div', {className: "gallery"},
        e('div', {className: "current-image"},
          e('img',{src: this.state.currentImage.image})
          ),
        images)
  }
}
document.addEventListener("DOMContentLoaded",
  function(event) {
    var images = [
    {% for image in object.productimage_set.all %}
        {"image": "{{ image.image.url|safe }}",
        "thumbnail": "{{ image.thumbnail.url|safe }}"},
    {% endfor %}
    ]
    ReactDOM.render(
        e(ImageBox, {images: images, imageStart: images[0]}),
        document.getElementById('imagebox')
    );
  });
</script>
{% endblock %}

Shopy/main/templates/main/product_list.html
{% extends "base.html" %}
{% block content %}

<h1>products</h1>
{% for product in page_obj %}
  <p>{{ product.name }}</p>
  <p>
    <a href="{% url "product" product.slug %}">See it here</a>
  </p>
  {% if not forloop.last %}
    <hr>
  {% endif %}
{% endfor %}
<nav>
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a
          class="page-link"
          href="?page={{page_obj.previous_page_number}}">Previous</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#">Previous</a>
      </li>
    {% endif %}
    {% for pagenum in page_obj.paginator.page_range %}
      <li
          class="page-item{% if page_obj.number == pagenum %} active{% endif %}">
           <a class="page-link" href="?page={{pagenum}}">{{pagenum}}</a>
        </li>
    {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
           <a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#">Next</a>
        </li>
      {% endif %}
    </ul>
  </nav>

{% endblock %}

Shopy/main/templates/main/signup.html
{% extends "base.html" %}
{% block content %}
<h2>Sign up</h2>
<p>Please fill the form below.</p>
<form method="POST">
  {% csrf_token %}
  <div class="form-group">
    {{ form.email.label_tag }}
    <input
      type="email"
      class="form-control {% if form.email.errors %}
is-­invalid{% endif %}"
      id="id_email"
      name="email"
      placeholder="Your email"
      value="{{ form.email.value|default:"" }}" >
      {% if form.email.errors %}
      <div class="invalid-feedback">
        {{ form.email.errors }}
      </div>
    {% endif %}
  </div>
  <div class="form-group">
    {{ form.password1.label_tag }}
    <input
      type="password"
      class="form-control {% if form.password1.errors %}
is-­invalid{% endif %}"
      id="id_password1"
      name="password1"
      value="{{ form.password1.value|default:"" }}">
    {% if form.password1.errors %}
      <div class="invalid-feedback">
        {{ form.password1.errors }}
      </div>
    {% endif %}
  </div>
  <div class="form-group">
    {{ form.password2.label_tag }}
    <input
      type="password"
      class="form-control{% if form.password2.errors %}
is-­invalid{% endif %}"
      id="id_password2"
      name="password2"
      value="{{ form.password2.value|default:"" }}">
      {% if form.password2.errors %}
      <div class="invalid-feedback">
        {{ form.password2.errors }}
      </div>
    {% endif %}
  </div>
   <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content %}